### ISSUE TITLE
How to put special styling on middle slide?

### ISSUE THREAD

**Issue by KhaVNguyen** [maxmarinich/react-alice-carousel#107]
I have three slides in my carousel and wish to add a border, different background color to the middle slide. What is the best way to achieve this?

**Comment by maxmarinich** [comment]
Hi, @KhaVNguyen! Try next:

```js
import React from 'react'
import AliceCarousel from 'react-alice-carousel'
import 'react-alice-carousel/lib/alice-carousel.css'

const Gallery = () => {
  return (
    <AliceCarousel mouseTrackingEnabled>
      <div  className="yours-custom-class" />
      <div className="yours-custom-class middle-slide-class" />
      <div  className="yours-custom-class" />
    </AliceCarousel>
  )
}
```

**Comment by KhaVNguyen** [comment]
Hi @maxmarinich thanks for helping out. 

I tried this but the result is the following: 
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/12026775/72509656-d733bd80-37fc-11ea-9e05-5843b8baf913.gif)

The style for the middle card is following that card when I slide next and previous instead of always remaining on the middle card.

I have setup my custom navigation buttons using the "props" example code that you provided.
Examples: 
`
  function slideNext() {
    props.setCurrentProductIndex(props.currentProductIndex + 1);
  }

  function slidePrev() {
    props.setCurrentProductIndex(props.currentProductIndex - 1);
  }`

` <AliceCarousel
        startIndex={1}
        responsive={responsive}
        slideToIndex={props.currentProductIndex}
        buttonsDisabled={true}
        dotsDisabled={true}
        infinite={true}
        onSlideChanged={e => {
          props.setCurrentProductIndex(e.item);
        }}
      >
        <ProductCard>1</ProductCard>
        <ProductCardMiddle>2</ProductCardMiddle>
        <ProductCard>3</ProductCard>
      </AliceCarousel>
`

**Comment by maxmarinich** [comment]
Hi, @KhaVNguyen! Live [demo](https://codesandbox.io/s/react-alice-carousel-stage-padding-example-qhsi0). Use next example:
```css
/* set rule for all, exclude first child */
.alice-carousel__stage-item.__active.__active + .__active {
  background-color: red;
}

/* reset rule for all, exclude second child */
.alice-carousel__stage-item.__active ~ .__active ~ .__active {
  background-color: transparent;
}

```
