### ISSUE TITLE
Custom arrow

### ISSUE THREAD

**Issue by MannyIOI** [maxmarinich/react-alice-carousel#143]
How do you create custom arrows on version 2. I was able to do it in version 1 but there is nothing in the docs that show to do it in version 2

**Comment by mr-fibonacci** [comment]
hi I have the same/ similar question as MannyIOI. I saw the readme GIFs with arrows on the side. Would it be possible to customize dots' position as well? The following image is what I'm looking for
![custom-arrow-dot-positioning](https://user-images.githubusercontent.com/37981639/98012383-f1bd3e80-1df0-11eb-89d2-729265fed47c.png)

**Comment by g-mayer** [comment]
I'm currently using the activeIndex and useState to render some custom dots and control the carousel. However, I feel like I should be using the slide methods (https://github.com/g-mayer/react-alice-carousel/tree/v2#methods) but I'm having trouble importing them.

**Comment by maxmarinich** [comment]
Hi, @mr-fibonacci! You can use [methods](https://github.com/maxmarinich/react-alice-carousel#methods) (like in the [v1](https://github.com/maxmarinich/react-alice-carousel/tree/v1#custom-prev--next-buttons-dots--thumbs-navigation)). The easiest way is css changes:
```css
.alice-carousel__prev-btn,
.alice-carousel__next-btn {
    position: absolute;
    top: 45px;
    width: auto;
    font-size: 70px;
}

.alice-carousel__next-btn {
   right: 0
}
```

![Снимок экрана 2020-11-16 в 9 24 00](https://user-images.githubusercontent.com/9882979/99219959-bfe3a900-27ee-11eb-9f7c-77770589be02.png)
