### ISSUE TITLE
Customize Carousel Dots

### ISSUE THREAD

**Issue by nkemcels** [maxmarinich/react-alice-carousel#145]
Thanks for creating this library. I'll like to customize the current dots for my carousel or to at least change it's color so that it matches the theme of my app.

**Comment by nkemcels** [comment]
I couldn't wait for the maintainer to do this change, so I created a pull request to ease the load. Here is it https://github.com/maxmarinich/react-alice-carousel/pull/146#issue-517868612.

**Comment by maxmarinich** [comment]
Hi, @nkemcels! You can use example form [v1](https://github.com/maxmarinich/react-alice-carousel/tree/v1#custom-prev--next-buttons-dots--thumbs-navigation). But the easiest way is to redefine the general css like in the screenshot:

```css 
.alice-carousel__dots-item {
  width: 20px;
  height: 20px;
}

.alice-carousel__dots-item.__active {
    background-color: red;
}
```

![Screenshot](https://user-images.githubusercontent.com/9882979/99140966-46fe1900-2657-11eb-81c8-903516a0cefc.jpg)
