### ISSUE TITLE
Issues when style is display: table

### ISSUE THREAD

**Issue by jaadchacra** [maxmarinich/react-alice-carousel#155]
If the carousel is placed in a container with style { display: table } it becomes unusuable

**Comment by maxmarinich** [comment]
Hi, @jaadchacra! This is a controversial case, and I'm not sure that the gallery should deal with it. But if you're looking for a solution, use the following:
```css
.alice-carousel {
    width: 0;
    min-width: 100%;
}
```
