### ISSUE TITLE
how to move dots in image?

### ISSUE THREAD

**Issue by mohammad-hassani** [maxmarinich/react-alice-carousel#270]
Hello, I wanted to know if there is a way to move the dots in the photo?

I wrote this code for custom dots
```jsx
const renderDotsItem = ({ isActive }) => {
    return isActive ? 
        <div className="w-8 h-3 mx-1 bg-white rounded-full"></div> 
    : 
        <div className="w-3 h-3 mx-1 rounded-full bg-battleship-grey"></div>;
};
```
and when I add the ‍‍‍‍`absolute` class with `bottom-32` (for example), all the dots placed on top of each other

**Comment by mohammad-hassani** [comment]
OK I added this class
```css
.alice-carousel__dots {
    position: absolute;
    bottom: 60px;
    width: 100%;
}
```
to my `app.css` file and every thing is fine now
