### ISSUE TITLE
How to put arrows for navigation on the sides like in the example

### ISSUE THREAD

**Issue by FabioTambu** [maxmarinich/react-alice-carousel#290]
I was looking at the example on Github (see attachment) and there the arrows are on the sides instead of the bottom, I searched how to do it but I didn't succeed, could you tell me how to do it?
![GitHub Example](https://github.com/maxmarinich/react-alice-carousel/assets/66631258/a40cf64f-3436-4386-9a08-98b3e400f3e9)

**Comment by maxmarinich** [comment]
Hi, @FabioTambu! 
There are some cases for it, the most common is pure css and carousel classnames (used [Basic Example](https://maxmarinich.github.io/react-alice-carousel/))
```css
.s-main {
  padding: 100px;
}
.alice-carousel__prev-btn {
    position: absolute;
    left: -50px;
    display: inline-block;
    top: 75px;
    text-align: left;
    width: 50px;
    height: 50px;
}

.alice-carousel__prev-btn-item {
    display: inline-block;
    border: solid 2px #465798;
    border-radius: 50%;
    width: 20px;
    height: 20px;
    text-align: center;
}
```

<img width="1347" alt="Screenshot 2023-09-08 at 10 49 23" src="https://github.com/maxmarinich/react-alice-carousel/assets/9882979/ae4aaee9-5280-47c1-afee-1786ab953e79">
